<MenuScreen>:
    BoxLayout:
        Button:
            text: "Go to settings"
            on_press: root.manager.current = "settings"
        Button:
            text: "Quit"
            on_press: app.stop()


<SettingsScreen>
    BoxLayout:
        Button:
            text: "Back to menu"
            on_press:
                root.manager.current = "menu"
        Button:
            text: "My settings"
